#pragma once

// From glfw3.h
#define NAVIA_MOUSE_BUTTON_1         0
#define NAVIA_MOUSE_BUTTON_2         1
#define NAVIA_MOUSE_BUTTON_3         2
#define NAVIA_MOUSE_BUTTON_4         3
#define NAVIA_MOUSE_BUTTON_5         4
#define NAVIA_MOUSE_BUTTON_6         5
#define NAVIA_MOUSE_BUTTON_7         6
#define NAVIA_MOUSE_BUTTON_8         7
#define NAVIA_MOUSE_BUTTON_LAST      NAVIA_MOUSE_BUTTON_8
#define NAVIA_MOUSE_BUTTON_LEFT      NAVIA_MOUSE_BUTTON_1
#define NAVIA_MOUSE_BUTTON_RIGHT     NAVIA_MOUSE_BUTTON_2
#define NAVIA_MOUSE_BUTTON_MIDDLE    NAVIA_MOUSE_BUTTON_3